# Generated by Django 3.2.4 on 2021-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseradetails',
            name='contactNumber',
            field=models.CharField(max_length=15),
        ),
    ]
